name: Master CI Build

on: [ push, pull_request ]


jobs:
  build:
    runs-on: windows-2019
    env:
      BUILD_TOOLS_PATH: C:\apps\build-tools\
    steps:
      - run: echo $env:BUILD_TOOLS_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt5
        uses: jurplel/install-qt-action@v3.3.0
        with:
          cache: true
          cache-key-prefix: windows-QtCache
          modules: qtwebengine

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.1

      - name: Build
        run: |
          cmake -G"NMake Makefiles JOM" -DCMAKE_BUILD_TYPE=Release .
          jom interface

      - name: Upload redist folder
        uses: actions/upload-artifact@v3
        with:
          name: interface
          path: interface